# Generated by Django 4.0.4 on 2022-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0006_alter_cliente_nombre_alter_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=50, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=9, verbose_name='telefono'),
        ),
    ]
